import { BookOpen, Compass, HeartHandshake, Target } from 'lucide-react';
import { Card } from '@/components/Card';
import { FellowshipArt } from '@/components/hero-art/FellowshipArt';
import { BibleStudyArt } from '@/components/hero-art/BibleStudyArt';
import { PrayerArt } from '@/components/hero-art/PrayerArt';

const CORE_VALUES = ['Prayer', 'Unity', 'Excellence', 'Integrity', 'The Word', 'Fellowship'];

export function AboutPage() {
  return <div className="overflow-hidden">
    <section className="mesh-hero-bg px-5 py-20 sm:px-6 sm:py-24"><div className="page-shell grid items-center gap-12 lg:grid-cols-2"><div><span className="eyebrow">Our story</span><h1 className="mt-6 text-5xl font-black tracking-tight text-primary-900 sm:text-6xl">Built around <span className="text-primary-500">Christ.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">TUMCU exists to reach students with the Gospel and equip believers to carry their faith into every corner of campus and beyond.</p></div><div className="surface-glass photo-frame p-8 sm:p-10"><FellowshipArt className="mx-auto w-full max-w-lg" /></div></div></section>

    <section className="page-shell section-pad"><div className="grid gap-8 lg:grid-cols-2"><Card variant="glass" className="p-8 sm:p-10"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary-900 text-white"><Compass size={22}/></div><h2 className="mt-6 text-2xl font-black text-primary-900">Vision</h2><p className="mt-3 leading-7 text-slate-600">A university community transformed by the Gospel of Jesus Christ — every student reached, every believer equipped, every graduate sent out as salt and light.</p></Card><Card variant="glass" className="p-8 sm:p-10"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gold-500 text-primary-900"><Target size={22}/></div><h2 className="mt-6 text-2xl font-black text-primary-900">Mission</h2><p className="mt-3 leading-7 text-slate-600">To reach every student at the Technical University of Mombasa with the Gospel, and equip believers for discipleship, leadership and service.</p></Card></div></section>

    <section className="page-shell space-y-12 pb-24"><div className="grid items-center gap-10 lg:grid-cols-2"><div className="surface-glass photo-frame p-8"><BibleStudyArt className="mx-auto w-full max-w-md" /></div><div><span className="text-xs font-black tracking-[.2em] text-gold-600">01 • THE WORD</span><h2 className="mt-3 text-4xl font-black text-primary-900">Scripture shapes the journey.</h2><p className="mt-4 leading-7 text-slate-600">TUMCU affirms the historic Christian faith and places the authority of Scripture at the centre of discipleship, teaching and daily life.</p></div></div><div className="grid items-center gap-10 lg:grid-cols-2 lg:[&>*:first-child]:order-2"><div className="surface-glass photo-frame p-8"><PrayerArt className="mx-auto w-full max-w-md" /></div><div><span className="text-xs font-black tracking-[.2em] text-gold-600">02 • PRAYER</span><h2 className="mt-3 text-4xl font-black text-primary-900">We seek God together.</h2><p className="mt-4 leading-7 text-slate-600">Prayer is not an item on the calendar. It is the posture of our community — interceding, listening, worshipping and trusting God.</p></div></div></section>

    <section className="page-shell pb-24"><Card variant="glass" className="p-8 sm:p-10"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-primary-50 text-primary-700"><BookOpen size={20}/></div><h2 className="text-2xl font-black text-primary-900">Core values</h2></div><div className="mt-7 flex flex-wrap gap-3">{CORE_VALUES.map((value) => <span key={value} className="rounded-full border border-primary-100 bg-white/60 px-5 py-2.5 text-sm font-bold text-primary-700">{value}</span>)}</div><div className="mt-8 flex items-start gap-3 rounded-3xl bg-primary-900 p-5 text-white"><HeartHandshake className="mt-1 shrink-0 text-gold-400" size={21}/><p className="text-sm leading-6 text-white/75">Our values are lived through community, service, discipleship and a commitment to love God and people well.</p></div></Card></section>
  </div>;
}
